name: Preprocessing Automation

on:
  push:
    paths:
      - 'preprocessing/automate_Muhammad-Dila.py'
      - 'dataset_raw/**'
  workflow_dispatch:

jobs:
  preprocessing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install pandas numpy

    - name: Run preprocessing script
      run: python preprocessing/automate_Muhammad-Dila.py

    - name: Upload processed dataset
      uses: actions/upload-artifact@v4
      with:
        name: dataset_preprocessing
        path: dataset_preprocessing/
